#!/bin/bash

#====================
#====================

COMPILER=GNU
#COMPILER=INTEL
PARALLEL=YES
#PARALLEL=NO # error
#SYSTEM=kashiwa

MPIDIR=/usr/bin
#====================
#====================

# ++++ installation directory ++++
INSTALL_DIR=`pwd`
# ++++ installation directory ++++

# ++++ current directory ++++
CURDIR=`pwd`
# ++++ current directory ++++


# ++++ macro options ++++
#DEB=-DDEB 
NORM=-DNORM 
#MONITOR=-DMONITOR
#CHANIJOB=-DCHAINJOB
#GRAPHIC=-DGRAPHIC
#PAPI=-PAPI
# ++++ macro options ++++

# ++++ cpplapack include dir ++++
#CPLADIR="-I/home/kota/local/cpplapack-2010.03.27/include -I/home/kota/local/include"
#CPLADIR="-I/home/kota/local/cpplapack-2010.03.27/include "
CPLADIR="-I$CURDIR/include "
#CPLADIR="-I$HOME/local/lib/cpplapack/include "
# ++++ cpplapack include dir ++++

#PAPIDIR="-I/usr/local/include"

# ++++ blas lapack dir ++++
#MKLBLAS="-lmkl_lapack -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -lguide -lpthread"
#LIBS="-L${MKLROOT}/lib/em64t ${MKLBLAS}"
LIBS="-lblas -llapack "
# for ice #
#LIBS="-lmkl=sequential"
#LIBS="-lblas -llapack /usr/local/lib/libpapi.a"
# ++++ blas lapack dir ++++

# ++++ profiler option ++++
PROF=
#PROF="-pg"
# ++++ PROFILER option ++++

LDFLAGS=

case $COMPILER in 
    GNU)
#	OPT="-O3 -mfpmath=sse -msse4.1 -ftree-vectorize"
#        DEBUG="-g -W -Wall -fbounds-check -ffpe-trap=zero,overflow,underflow"
	OPT="-O2"
	
	case $PARALLEL in
	    YES)
		CXX=$MPIDIR/mpic++
		CC=$MPIDIR/mpic++
		MULTI=-DMULTI;;
	    NO)
		CXX=g++-4.6
		CC=g++-4.6;;
	esac;;
    INTEL)
	OPT="-O2 "
#DEBUG="-g -CU -CB"
	
	case $PARALLEL in
	    YES)
		CXX=$MPIDIR/mpiCC
		CC=$MPIDIR/mpiCC
		MULTI=-DMULTI;;
	    NO)
		CXX=icpc
		CC=icpc;;
	esac;;
esac

case $SYSTEM in 
    kashiwa)
	CXX=icpc
	CC=icpc
	MULTI=-DMULTI
	OPT="-O2 -lmpi "
	LIBS="-mkl=sequential"
	KASHIWA="-DKASHIWA"
esac


CPPFLAGS="${DEB} ${NORM} ${MONITOR} ${CHAINJOB} ${GRAPHIC} ${MULTI} ${PAPI} ${KASHIWA}"
CXXFLAGS="${OPT} ${DEBUG} ${CPPFLAGS} ${CPLADIR} ${PROF} ${PAPIDIR}"


# +++ option summary +++
echo 
echo "++++++ option summary ++++++"
echo "CC       = $CC"                     #C compiler command
echo "CXX      = $CXX"                    #C++ compiler command
echo "CXXFLAGS = $CXXFLAGS"               #C++ compiler flags
echo "CPPFLAGS = $CPPFLAGS"               #Preprocessor flags
echo "LDFLAGS  = $LDFLAGS"                #Linker flags
echo "LIBS     = $LIBS"                   #Libraries
echo "INSTALL DIRECTORY = $INSTALL_DIR"   #installation directory
echo "++++++ option summary ++++++"
echo 

# +++ option summary +++

# +++  configure +++
./configure \
  --prefix="${INSTALL_DIR}" \
   LIBS="${LIBS}" \
   CC=${CC} \
   CXX=${CXX} \
   CPPFLAGS="${CPPFLAGS}" \
   CXXFLAGS="${CXXFLAGS}" \
   LDFLAGS="${LDFLAGS}"

# +++  configure +++
